apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: transaction-validator-monitor
  namespace: monitoring
  labels:
    app: transaction-validator
spec:
  selector:
    matchLabels:
      app: transaction-validator
  namespaceSelector:
    matchNames:
      - payflow
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics